Fixes wrong path variable
FullPath is not defined/part of any surrounding select statement and hence not known to the query. This artifact fails with:

```
ERROR: Symbol FullPath not found. Current Scope is: ...
```